apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  params:
    - default: Unknown commit
      description: The commit comment from the push notification
      name: commit-comment
      type: string
  resources:
    - name: service-domain-git
      type: git
    - name: service-domain-image
      type: image
  tasks:
    - name: echo-git-commit-comment
      params:
        - name: comment
          value: $(params.commit-comment)
      taskRef:
        kind: Task
        name: echo-git-commit-comment
    - name: build-backend
      params:
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_ARGS_APPEND
          value: '-DNEXUSREPO=http://nexus-nexus-system.apps.cluster-2d0b.green.osp.opentlc.com/repository/releases/'
      resources:
        inputs:
          - name: source
            resource: service-domain-git
        outputs:
          - name: image
            resource: service-domain-image
      taskRef:
        kind: ClusterTask
        name: s2i-java-11

